<?php

/**
 * Takes an array of keys to strings, probably generated by
 * ConfigSchema_StringHashParser
 */
class ConfigSchema_StringHashAdapter
{
    
    /**
     * Takes a string hash and calls the appropriate functions in $schema
     * based on its values.
     */
    public function adapt($hash, $schema) {
        list($ns, $directive) = explode('.', $hash['ID'], 2);
        $default      = eval("return {$hash['DEFAULT']};");
        $type         = $hash['TYPE'];
        $description  = $hash['DESCRIPTION'];
        $schema->add($ns, $directive, $default, $type, $description);
    }
    
}
